### ISSUE TITLE
运行py脚本出错

### ISSUE THREAD

**Issue by y409663780** [xujiaji/FlutterAssetsSync#1]
![image](https://user-images.githubusercontent.com/7691251/83327231-e186bd80-a2ac-11ea-8c83-e178d08392f2.png)
是不是http://127.0.0.1:3333这个地址的问题？

**Comment by xujiaji** [comment]
文件应该已经生成了。可以试试看看在cmd中能不能执行：`python3 -m http.server 3333`

**Comment by y409663780** [comment]
可以执行，调整了一下代码，脚本可以使用，谢谢你的分享

**Comment by xujiaji** [comment]
👌
